on: [ push, pull_request ]
name: pytest test validation
jobs:
    pytest:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
            options: --privileged --capability=CAP_MKNOD --device-cgroup-rule="b 7:* rmw"
        steps:
            - uses: actions/checkout@v2
            - run: pacman --noconfirm -Syu python python-pip parted
            - run: python -m pip install --upgrade pip
            - run: pwd
            - run: ls -la
            - run: pip install .
            - run: pip install pytest
            - name: Test with pytest
              run: python -m pytest