# This workflow will build Python packages on every commit.

name: Build archinstall

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-pip python-pyparted python-simple-term-menu pkgconfig gcc
      - name: Install build dependencies
        run: |
          python -m pip install --break-system-packages --upgrade pip
          pip install --break-system-packages --upgrade build twine wheel setuptools installer
          pip uninstall archinstall -y --break-system-packages
      - name: Build archinstall
        run: python -m build --wheel --no-isolation
      - name: Install archinstall
        run: python -m installer dist/*.whl
      - name: Run archinstall
        run: |
          python -V
          archinstall --script guided -v
          archinstall --script swiss -v
          archinstall --script only_hd -v
          archinstall --script minimal -v
      - uses: actions/upload-artifact@v4
        with:
          name: archinstall
          path: dist/*
