on:
    push:
        paths:
        - 'archinstall/locales/**'
    pull_request:
        paths:
        - 'archinstall/locales/**'
name: translation file checks
jobs:
    translation-check:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - uses: actions/checkout@v4
            - run: pacman --noconfirm -Syu python
            - run: cd archinstall/locales
            - run: pwd
            - run: ls -l
            - run: bash locales_generator.sh
            - run: git diff --name-only
            - run: ls
